

# Markdown

highlighter: true

# Defaults

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: "default"
      og_type: article
      type: article
      category: "Others"
      excerpt_separator: "<!--more-->"
      prism_languages: []

# Site info

url: https://gonetwifi.github.io
title: Changelog gonetwifi

repository:gonetwifi/gonetwifi
